# Generated by Django 2.0.5 on 2018-07-28 00:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(default='Some text', verbose_name='Body Text'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 7, 28, 0, 49, 59, 903828, tzinfo=utc)),
        ),
    ]
