# Generated by Django 2.0.5 on 2018-07-28 02:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180728_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 7, 28, 2, 48, 38, 428282, tzinfo=utc)),
        ),
    ]
