# Generated by Django 2.0.5 on 2018-07-28 02:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180728_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 7, 28, 2, 50, 43, 384608, tzinfo=utc)),
        ),
    ]
