# Generated by Django 2.0.5 on 2018-07-29 17:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180728_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 7, 29, 17, 53, 47, 225055, tzinfo=utc)),
        ),
    ]
